
# Copyright (c) 2015-2018 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#Installation for Postgres servers

- name: Updating apt cache if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
  - postgresql

- name: Installing Postgres packages
  apt:
    name: [postgresql-9.6, ufw]
    state: latest
  tags:
  - postgresql

#TODO: change the default password to something that won't be hit automatically

- name: Allowing Postgres connections through the firewall (ufw, port 5432)
  ufw:
    rule: allow
    port: 5432
  tags:
  - network
  - postgresql
  - security

#TODO: should this be optional?
- name: Configuring Postgresql to listen on 0.0.0.0 (set listen_addresses
  replace:
    path: /etc/postgresql/9.6/main/postgresql.conf
    regexp: "^#listen_addresses = 'localhost'"
    replace: "#listen_addresses = '*'"
    backup: yes
  notify:
  - restart postgresql
  tags:
  - postgresql

#TODO: setup backups
