
# Copyright (c) 2015-2019 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#Sets the time zone

#TODO: configured based on site (e.g. America/Chicago)

- name: Setting time zone
  timezone:
    name: Etc/UTC
  notify: restart crond
  tags:
    - time
    - timezone

- name: Updating apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags:
    - packages
    - security
    - time

- name: Installing NTP
  apt:
    name: [ntp]
    state: latest
  tags:
    - packages
    - security
    - time

- name: Enabling NTP
  service:
    name: ntp
    state: started
    enabled: yes
  tags:
    - security
    - services
    - time

- name: Restricting cron to authorized users (checking if /etc/cron.allow exists)
  stat:
    path: /etc/cron.allow
  register: cron_allow_check
  tags:
    - cron
    - filesystem
    - security
    - time

- name: Restricting cron to authorized users (setting owner/group owner on /etc/cron.allow)
  file:
    path: /etc/cron.allow
    owner: root
    group: root
  when:
    - cron_allow_check is defined
    - cron_allow_check.stat.exists
  tags:
    - cron
    - filesystem
    - security
    - time

- name: Restricting cron to authorized users (removing cron.deny)
  file:
    path: /etc/cron.deny
    state: absent
  tags:
    - cron
    - filesystem
    - security
    - time

- name: Restricting cron to authorized users (checking if /etc/at.allow exists)
  stat:
    path: /etc/cron.allow
  register: cron_allow_check
  tags:
    - cron
    - filesystem
    - security
    - time

- name: Restricting cron to authorized users (setting owner/group owner on /etc/at.allow)
  file:
    path: /etc/cron.allow
    owner: root
    group: root
  when:
    - cron_allow_check is defined
    - cron_allow_check.stat.exists
  tags:
    - cron
    - filesystem
    - security
    - time

- name: Restricting at to authorized users (removing at.deny)
  file:
    path: /etc/at.deny
    state: absent
  tags:
    - cron
    - security
    - time

- name: Enabling cron
  service:
    name: cron
    state: started
    enabled: yes
  tags:
    - cron
    - security
    - services
    - time
