
# Copyright (c) 2015-2018 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#Configures sshd

- name: Configuring sshd (client alive interval = 120s)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ClientAliveInterval"
    line: "ClientAliveInterval 120"
    state: present
  notify: restart sshd
  tags:
    - security
    - ssh

- name: Configuring sshd (client alive count max = 30s)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ClientAliveCountMax"
    line: "ClientAliveCountMax 30"
    state: present
  notify: restart sshd
  tags:
    - security
    - ssh

- name: Configuring sshd (disabling RSH emulation)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^IgnoreRhosts"
    line: "IgnoreRhosts yes"
    state: present
  notify: restart sshd
  tags:
    - security
    - ssh

- name: Configuring sshd (disallowing empty passwords)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
    state: present
  notify: restart sshd
  tags:
    - security
    - ssh

- name: Configuring sshd (disabling password authentication)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart sshd
  tags:
    - security
    - ssh

- name: Configuring sshd (enabling pubkey authentication)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
  notify: restart sshd
  tags:
    - security
    - ssh

- name: Enabling sshd
  service:
    name: ssh
    state: started
    enabled: yes
  tags:
    - security
    - services
    - ssh
