
stages:
  - test

smoke_test_job:
  stage: test
  script:
    - scripts/AugmentLines.py -h
    - scripts/CsvToJson.py -h
    - scripts/GenerateConfigs.py -h
    - scripts/JsonToXml.py -h
    - scripts/Parallelize.py -h
    - scripts/RandomSleep.py 0 2
    - scripts/Template.py -h

    - scripts/check_config.sh
    - scripts/git
    - scripts/hg
  only:
    - master
