
before_script:

stages:
  - test

smoke_test_job:
  stage: test
  script:
    - scripts/AugmentLines.py -h
    - scripts/check_config.sh
    - scripts/CsvToJson.py -h
    - scripts/git
    - scripts/hg
    - scripts/JsonToXml.py -h
  only:
    - master
