
stages:
  - test

help_test_job:
  stage: test
  script:
    - scripts/AugmentLines.py -h
    - scripts/CsvToJson.py -h
    - scripts/GenerateConfigs.py -h
    - scripts/JsonToXml.py -h
    - scripts/OrganizeTimestampedFiles.py -h
    - scripts/Parallelize.py -h
    - scripts/Prepend.py -h
    - scripts/RandomSleep.py -h
    - scripts/SpacesToTabs.py -h
    - scripts/TabsToSpaces.py -h
    - scripts/Template.py -h
    - scripts/WatchFiles.py -h

    - "! scripts/create_ramdisk.sh"
    - "! scripts/git_author_files.sh"
    - "! scripts/git_author_line_counts.sh"
    - "! scripts/git_file_authors.sh"
    - "! scripts/git"
    - "! scripts/hg"
    - "! scripts/upgrade_python3_venv.sh"
  only:
    - master

functional_test_check_config_job:
  stage: test
  script:
    - scripts/check_config.sh
  only:
    - master

functional_test_parallelize_job:
  stage: test
  script:
    #Not the most traditional use of this script, but since the "run ID" is 0,
    #it will make the random sleeps be between 0 and n seconds
    - time scripts/Parallelize.py -p 2 -s 1 scripts/RandomSleep.py 0 4 2 3 3 4 3 2 3
  only:
    - master

functional_test_sleep_job:
  stage: test
  script:
    - time scripts/RandomSleep.py 0 1
    - time scripts/RandomSleep.py 1 3
  only:
    - master

functional_test_spaces_tabs_job:
  stage: test
  script:
    #These should be commutative and idempotent when applied repeatedly
    #Original script starts with tabs
    - TEST_SCRIPT=scripts/Parallelize.py
    - cp $TEST_SCRIPT Test.py
    - scripts/SpacesToTabs.py Test.py
    - diff $TEST_SCRIPT Test.py
    - scripts/TabsToSpaces.py Test.py
    - "! diff $TEST_SCRIPT Test.py"
    - scripts/SpacesToTabs.py Test.py
    - diff $TEST_SCRIPT Test.py
    - rm Test.py
  only:
    - master
