
# Copyright (c) 2015-2018 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

- name: Downloading setup script
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/gitlab_runner_script.deb.sh
  tags:
    - gitlab_ci

- name: Setting up dependencies
  command: bash /tmp/gitlab_runner_script.deb.sh
  tags:
    - gitlab_ci

- name: Updating apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags:
    - gitlab_ci
    - packages

- name: Installing supporting packages
  apt:
    name: [libboost-dev, make, pyflakes3, pylint, shellcheck, valgrind]
    state: latest
  tags:
    - gitlab_ci
    - packages

- name: Installing Gitlab CI runner
  apt:
    name: gitlab-runner
    state: latest
  register: apt_result
  notify:
    - restart gitlab-runner
  tags:
    - gitlab_ci
    - packages

#TODO: figure out how to incorporate gitlab-runner register

- name: Starting Gitlab CI runner service
  systemd:
    name: gitlab-runner
    state: started
    enabled: yes
  tags:
    - gitlab_ci
