
# Copyright (c) 2015-2018 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#Installation for SDR hosts

- name: Updating apt cache if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - sdr

- name: Installing SDR packages
  apt:
    name: [git, gqrx-sdr, libck-dev, libjansson-dev, librtlsdr-dev, rtl-sdr]
    state: latest
  tags:
    - sdr

- name: Creating account
  user:
    name: sdr
    comment: SDR
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: ed25519
  tags:
    - sdr

- name: Cloning TSL SDR repository
  git:
    repo: https://github.com/pvachon/tsl-sdr.git
    dest: /home/sdr/tsl-sdr/
  become: yes
  become_user: sdr
  tags:
    - sdr

- name: Configuring TSL SDR build
  command: ./waf configure
  args:
    chdir: /home/sdr/tsl-sdr/
  become: yes
  become_user: sdr
  tags:
    - sdr

- name: Building TSL SDR
  command: ./waf build
  args:
    chdir: /home/sdr/tsl-sdr/
  become: yes
  become_user: sdr
  tags:
    - sdr
