
# Copyright (c) 2015-2023 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#Installation for SDR hosts

- name: Updating apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags:
    - packages
    - sdr

- name: Installing SDR packages
  apt:
    name: [build-essential, git, gqrx-sdr, libck-dev, libjansson-dev, librtlsdr-dev, nasm, pkg-config, rtl-sdr]
    state: latest
  tags:
    - packages
    - sdr

- name: Creating account
  user:
    name: sdr
    comment: SDR
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: ed25519
  tags:
    - sdr

- name: Cloning TSL repository
  git:
    repo: https://github.com/pvachon/tsl.git
    dest: /home/sdr/tsl/
  become: yes
  become_user: sdr
  tags:
    - sdr

- name: Building TSL
  command: ./waf configure build
  args:
    chdir: /home/sdr/tsl/
  register: tsl_build_result
  changed_when: "'Compiling' in tsl_build_result.stdout or 'Linking' in tsl_build_result.stdout"
  become: yes
  become_user: sdr
  tags:
    - sdr

#This is intentionally run as root
- name: Installing TSL
  command: ./waf install
  args:
    chdir: /home/sdr/tsl/
  changed_when: False #There's probably a better way to suppress this...
  tags:
    - sdr

- name: Cloning TSL SDR repository
  git:
    repo: https://github.com/pvachon/tsl-sdr.git
    dest: /home/sdr/tsl-sdr/
  become: yes
  become_user: sdr
  tags:
    - sdr

- name: Building TSL SDR
  command: ./waf configure build
  args:
    chdir: /home/sdr/tsl-sdr/
  register: tslsdr_build_result
  changed_when: "'Compiling' in tslsdr_build_result.stdout or 'Linking' in tslsdr_build_result.stdout"
  become: yes
  become_user: sdr
  tags:
    - sdr
