#!/bin/bash

set -u

NC='\033[00m'
RED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'

for DIR in `ls -F | grep /`
do
	if [ -d $DIR/.git ]
	then
		BASE=`basename ${DIR}`
		echo -e "${BLUE}****************************** ${BASE} ******************************${NC}"
		echo
		cd $DIR
		git $@
		cd ..
		echo
	fi
done
