#!/bin/bash

set -u

readonly NC='\033[00m'
readonly RED='\033[1;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'

readonly OLD_PWD=`pwd`

for DIR in `find . -maxdepth 3 -name .git -type d` ; do
	BASE=`dirname ${DIR}`
	echo -e "${BLUE}****************************** ${BASE} ******************************${NC}"
	echo
	cd $BASE
	git "$@"
	cd $OLD_PWD
	echo
done
