#!/bin/bash

set -u

NC='\033[00m'
RED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'

OLD_PWD=`pwd`

for DIR in `find . -name .git -type d -maxdepth 3`
do
	BASE=`dirname ${DIR}`
	echo -e "${BLUE}****************************** ${BASE} ******************************${NC}"
	echo
	cd $BASE
	git $@
	cd $OLD_PWD
	echo
done
