#!/bin/bash

set -u

readonly NC='\033[00m'
readonly RED='\033[1;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'

for DIR in $(ls -F | grep /) ; do
	if [ -d $DIR/.hg ] ; then
		BASE=`basename ${DIR}`
		echo -e "${BLUE}****************************** ${BASE} ******************************${NC}"
		echo
		cd $DIR
		hg $@
		cd ..
		echo
	fi
done
